### ISSUE TITLE
FunC Cookbook Completion Tracker

### ISSUE THREAD

**Issue by Swafox** [VopxTech/func-examples#1]
List of all FunC Cookbook examples and their status of being wrapped into a runnable blueprint project 👇

### Basic Functionality ✅

- [X] BlankProject
- [X] SimpleCounter
- [X] How to write an if statement
- [X] How to write a repeat loop
- [x] How to write a while loop
- [x] How to write a do until loop

### Mathematics ✅

- [x] How to raise number to the power of n
- [x] How to generate random number
- [x] Modulo operations
- [x] How to get current time

### Sending Messages ✅

- [x] How to build an internal message cell
- [x] How to contain a body as ref to an internal message cell
- [x] How to contain a body as slice to an internal message cell
- [x] How to send a simple message
- [x] How to send a message with an incoming account
- [x] How to send a message with the entire balance
- [x] How to send a message with a long text comment
- [x] Generate internal address (out of scope)
- [x] Generate external address (out of scope)

### Comparison

- [ ] How to determine if slice is empty
- [ ] How to determine if slice is empty (doesn't have any bits, but may have refs)
- [ ] How to determine if slice is empty (doesn't have any refs, but may have bits)
- [ ] How to determine if cell is empty
- [ ] How to determine if dict is empty
- [ ] How to determine if tuple is empty
- [ ] How to determine if lisp style list is empty
- [ ] How to determine a state of the contract is empty
- [ ] Determine if slices are equal
- [ ] Determine if cells are equal

### Type conversion

- [ ] Resolving type X
- [ ] How to convert string to int
- [ ] How to convert int to string

### Tuples

- [ ] How to iterate tuples in both directions
- [ ] Reversing tuples
- [ ] Determine if tuples are equal
- [ ] Iterating n-nested tuples
- [ ] Basic operations with tuples

### Dictionaries

- [ ] How to store and load dictionary in local storage
- [ ] How to iterate dictionaries
- [ ] How to delete value from dictionaries

### Miscellaneous

- [ ] How to write own functions using asm keyword
- [ ] How to throw errors
- [ ] How to remove an item with a certain index from the list
- [ ] How to get only data bits from a slice without refs
- [ ] How to define your own modifying method
- [ ] How to iterate cell tree recursively

### stateInit

- [ ] How to iterate through lisp style list
- [ ] How to send a deploy message with stateInit only with stateInit and body
- [ ] How to build a stateInit cell
- [ ] How to calculate a contract address using stateInit
